#ifndef CMDSKEY_H
#define CMDSKEY_H


#define key_server_ip                       "tcpAddr"
#define key_server_port                     "tcpPort"
#define key_wifi_ssid                       "wifi/ssid"
#define key_wifi_psk                        "wifi/psk"
#define key_user_language                   "user/language"
#define key_user_protocol                   "user/protocol"
#define key_manual_config                   "manual/config"
#define key_manual_ip                       "manual/ip"
#define key_manual_netmask                  "manual/netmask"
#define key_manual_route                    "manual/route"
#define key_manual_dns                      "manual/dns"
#define key_openMode_openDoorMode           "openMode/openDoorMode"
#define key_switch_isTemp                   "switch/isTemp"
#define key_switch_isEg                     "switch/isEg"
#define key_switch_isIr                     "switch/isIr"
#define key_switch_isVi                     "switch/isVi"
#define key_switch_isLoose                  "switch/isLoose"
#define key_temp_warnValue                  "temp/warnValue"
#define key_temp_comp                       "temp/comp"
#define key_temp_abnormalOpen               "temp/abnormalOpen"
#define key_temp_thresholdUpdateTime        "temp/thresholdUpdateTime"
#define key_identify_value                  "identify/value"
#define key_identify_waitTime               "identify/waitTime"
#define key_user_wg                         "user/wg"
#define key_user_volume                     "user/volume"
#define key_user_name                       "user/name"
#define key_user_doorDelayTime             "user/doorDelayTime"
#define key_user_isFahrenheit               "user/isFahrenheit"
#define key_user_tempBroadcastForm          "user/tempBroadcastForm"
#define key_user_isUploadStrangerAccess     "user/isUploadStrangerAccess"
#define key_user_isUploadUserWithPhoto      "user/isUploadUserWithPhoto"
#define key_user_isMaskRecognition          "user/isMaskRecognition"
#define key_user_cameraDistance             "user/cameraDistance"
#define key_power_sleepMode                 "power/sleepMode"
#define key_power_sleepTime                 "power/sleepTime"
#define key_FactorySetup                    "FactorySetup"
#define key_reboot                          "reboot"
#define key_versionUpdate                   "versionUpdate"
//#define key_OTAUpdate                       "OTAUpdate"

#endif // CMDSKEY_H
